// Copyright (C) 2026 Panos Stokas <panos.stokas@hotmail.com>
// Error handler headers

#ifndef ERROR_HANDLER_H
#define ERROR_HANDLER_H

enum ErrorCode {
	NO_ERROR,
	OPEN_TEMPLATE,
	MAX_LENGTH_EXCEEDED,
	MEMORY_ALLOCATION_ERROR,
	LABEL,
	DEFINED_LABEL,
	EMPTY_STRING,
	UNCLOSED_STRING,
	ARRAY_ELEMENT,
	SPEED,
	NUMBER,
	MANY_LABELS,
	DUPLICATE_LABEL,
	EXTRANEOUS,
	DIRECTIVE,
	INSTRUCTION,
	RESERVED,
	REGISTER,
	VALUE,
	COMMA,
	LEFTBRACKET,
	RIGHTBRACKET,
	OP2,
	RAM_LIMIT,
	UNQUOTED_TITLE,
	DUPLICATE_TITLE
};

enum NumErrorCode {
	NUMBER_ERROR = -1,
	HEX_ERROR = -2,
	BIN_ERROR = -3,
	OCTAL_ERROR = -4,
	SIGNED_RANGE_ERROR = -5,
	RANGE_ERROR = -6
};

void error(enum ErrorCode errorlevel);

#endif
