-- Generated by the E80 assembler
LIBRARY ieee; USE ieee.std_logic_1164.ALL, work.support.ALL;
PACKAGE program IS
CONSTANT SIMDIP_directive  : WORD    := "00000000";
CONSTANT SPEED_directive   : NATURAL := 2;
CONSTANT MONITOR_directive : NATURAL := 0;
CONSTANT Program : WORDx256  := (
-- MACHINE_CODE_PLACEHOLDER
OTHERS => "UUUUUUUU");END;